version: '3'
services:
  backend:
    container_name: desafio-tech
    restart: unless-stopped
    volumes:
      - ~/data:/root/data
    networks:
      - desafio-tech-network
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '7001:7001'
    expose: 
      - '7001'
networks:
  desafio-tech-network:
    driver: bridge
